<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\Blog;
use App\Models\HeroSlider;
use App\Models\Offer;
use App\Models\ShippingDistrict;
use App\Models\FooterSetting;
use Illuminate\Database\Seeder;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        // ============================================================
        // BRANDS
        // ============================================================
        $brands = [
            ['name' => 'Rolex', 'slug' => 'rolex', 'description' => 'The world\'s most recognized watch brand.', 'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Rolex_logo.svg/200px-Rolex_logo.svg.png', 'is_featured' => true],
            ['name' => 'Omega', 'slug' => 'omega', 'description' => 'Swiss luxury watchmaker famous for the Speedmaster.', 'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Omega_Logo.svg/200px-Omega_Logo.svg.png', 'is_featured' => true],
            ['name' => 'Tag Heuer', 'slug' => 'tag-heuer', 'description' => 'Renowned for sports watches and chronographs.', 'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Tag_Heuer_Logo.svg/200px-Tag_Heuer_Logo.svg.png', 'is_featured' => true],
            ['name' => 'Seiko', 'slug' => 'seiko', 'description' => 'Japanese watchmaker known for innovation.', 'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Seiko_logo.svg/200px-Seiko_logo.svg.png', 'is_featured' => true],
            ['name' => 'Citizen', 'slug' => 'citizen', 'description' => 'Solar-powered watches and precision timepieces.', 'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Citizen_Logo.svg/200px-Citizen_Logo.svg.png', 'is_featured' => true],
            ['name' => 'Nepal Time', 'slug' => 'nepal-time', 'description' => 'Proudly Nepali watch brand.', 'logo' => 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=200&h=200&fit=crop', 'is_featured' => true],
            ['name' => 'Kathmandu Watches', 'slug' => 'kathmandu-watches', 'description' => 'Local Nepali brand crafting elegant watches.', 'logo' => 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=200&h=200&fit=crop', 'is_featured' => true],
            ['name' => 'Himalayan Horology', 'slug' => 'himlayan-horology', 'description' => 'Luxury watches inspired by the Himalayas.', 'logo' => 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=200&h=200&fit=crop', 'is_featured' => true],
        ];

        foreach ($brands as $data) {
            Brand::create($data);
        }

        // ============================================================
        // CATEGORIES
        // ============================================================
        $categories = [
            ['name' => 'Luxury', 'slug' => 'luxury', 'description' => 'Premium luxury watches', 'sort_order' => 1],
            ['name' => 'Sports', 'slug' => 'sports', 'description' => 'Sports and diving watches', 'sort_order' => 2],
            ['name' => 'Dress', 'slug' => 'dress', 'description' => 'Elegant dress watches', 'sort_order' => 3],
            ['name' => 'Automatic', 'slug' => 'automatic', 'description' => 'Automatic movement watches', 'sort_order' => 4],
            ['name' => 'Quartz', 'slug' => 'quartz', 'description' => 'Quartz movement watches', 'sort_order' => 5],
            ['name' => 'Diver', 'slug' => 'diver', 'description' => 'Professional diving watches', 'sort_order' => 6],
            ['name' => 'Chronograph', 'slug' => 'chronograph', 'description' => 'Chronograph watches', 'sort_order' => 7],
            ['name' => 'Nepali Heritage', 'slug' => 'nepali-heritage', 'description' => 'Watches inspired by Nepali culture', 'sort_order' => 8],
            ['name' => 'Limited Edition', 'slug' => 'limited-edition', 'description' => 'Exclusive limited edition timepieces', 'sort_order' => 9],
            ['name' => 'Men', 'slug' => 'men', 'description' => 'Men\'s watches', 'sort_order' => 10],
            ['name' => 'Women', 'slug' => 'women', 'description' => 'Women\'s watches', 'sort_order' => 11],
            ['name' => 'Unisex', 'slug' => 'unisex', 'description' => 'Unisex watches', 'sort_order' => 12],
        ];

        foreach ($categories as $data) {
            Category::create($data);
        }

        // ============================================================
        // PRODUCTS (matching frontend sample data)
        // ============================================================
        $products = [
            [
                'name' => 'Rolex Submariner Date',
                'slug' => 'rolex-submariner-date',
                'description' => 'The iconic diver\'s watch with Cerachrom bezel and Chromalight display.',
                'short_description' => 'Iconic diving watch with 41mm case and automatic movement.',
                'sku' => 'RLX-126610LN',
                'price' => 450000,
                'compare_price' => 480000,
                'final_price' => 450000,
                'discount_percentage' => 6,
                'stock_quantity' => 5,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Automatic',
                'strap' => 'Oystersteel',
                'case_material' => 'Oystersteel',
                'case_diameter' => '41mm',
                'case_thickness' => '12.5mm',
                'water_resistance' => '300m',
                'dial_color' => 'Black',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '5 years',
                'average_rating' => 4.8,
                'reviews_count' => 124,
                'brand_id' => 1,
                'images' => ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400',
                'categories' => ['luxury', 'diver', 'men', 'automatic'],
            ],
            [
                'name' => 'Omega Speedmaster Professional',
                'slug' => 'omega-speedmaster-professional',
                'description' => 'The legendary Moonwatch that has been part of all six moon landings.',
                'short_description' => 'Iconic chronograph with Hesalite crystal and manual movement.',
                'sku' => 'OMG-31130423001006',
                'price' => 380000,
                'compare_price' => null,
                'final_price' => 380000,
                'discount_percentage' => 0,
                'stock_quantity' => 8,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Manual',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '42mm',
                'case_thickness' => '13.8mm',
                'water_resistance' => '50m',
                'dial_color' => 'Black',
                'glass_type' => 'Hesalite Crystal',
                'warranty_period' => '3 years',
                'average_rating' => 4.9,
                'reviews_count' => 89,
                'brand_id' => 2,
                'images' => ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400',
                'categories' => ['luxury', 'chronograph', 'men'],
            ],
            [
                'name' => 'Nepal Time Himalayan Classic',
                'slug' => 'nepal-time-himalayan-classic',
                'description' => 'Proudly Nepali timepiece inspired by the majestic Himalayas.',
                'short_description' => 'Handcrafted watch with traditional Nepali motifs and Swiss movement.',
                'sku' => 'NT-HC-001',
                'price' => 25000,
                'compare_price' => 30000,
                'final_price' => 25000,
                'discount_percentage' => 17,
                'stock_quantity' => 20,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_best_seller' => false,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '40mm',
                'case_thickness' => '10mm',
                'water_resistance' => '50m',
                'dial_color' => 'White',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '2 years',
                'average_rating' => 4.5,
                'reviews_count' => 23,
                'brand_id' => 6,
                'images' => ['https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400',
                'categories' => ['nepali-heritage', 'unisex', 'automatic'],
            ],
            [
                'name' => 'Kathmandu Heritage Edition',
                'slug' => 'kathmandu-heritage-edition',
                'description' => 'Elegant timepiece celebrating Kathmandu\'s rich cultural heritage.',
                'short_description' => 'Limited edition watch with traditional Nepali artistry.',
                'sku' => 'KW-HE-002',
                'price' => 35000,
                'compare_price' => null,
                'final_price' => 35000,
                'discount_percentage' => 0,
                'stock_quantity' => 10,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_best_seller' => false,
                'is_limited_edition' => true,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '38mm',
                'case_thickness' => '9mm',
                'water_resistance' => '30m',
                'dial_color' => 'Blue',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '3 years',
                'average_rating' => 4.7,
                'reviews_count' => 15,
                'brand_id' => 7,
                'images' => ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400',
                'categories' => ['nepali-heritage', 'unisex', 'limited-edition', 'automatic'],
            ],
            [
                'name' => 'Tag Heuer Carrera',
                'slug' => 'tag-heuer-carrera',
                'description' => 'Inspired by motor racing, the Carrera is a symbol of speed and precision.',
                'short_description' => 'Sporty chronograph with tachymeter bezel.',
                'sku' => 'TH-CAR-011',
                'price' => 185000,
                'compare_price' => 200000,
                'final_price' => 185000,
                'discount_percentage' => 8,
                'stock_quantity' => 12,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '44mm',
                'case_thickness' => '13mm',
                'water_resistance' => '100m',
                'dial_color' => 'Black',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '2 years',
                'average_rating' => 4.6,
                'reviews_count' => 67,
                'brand_id' => 3,
                'images' => ['https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=400',
                'categories' => ['luxury', 'chronograph', 'men', 'sports'],
            ],
            [
                'name' => 'Seiko Prospex Diver',
                'slug' => 'seiko-prospex-diver',
                'description' => 'Professional diving watch with exceptional water resistance.',
                'short_description' => '200m diver with automatic movement and LumiBrite dial.',
                'sku' => 'SKX-007',
                'price' => 45000,
                'compare_price' => 50000,
                'final_price' => 45000,
                'discount_percentage' => 10,
                'stock_quantity' => 25,
                'in_stock' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Automatic',
                'strap' => 'Rubber',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '42mm',
                'case_thickness' => '13mm',
                'water_resistance' => '200m',
                'dial_color' => 'Black',
                'glass_type' => 'Hardlex Crystal',
                'warranty_period' => '2 years',
                'average_rating' => 4.4,
                'reviews_count' => 156,
                'brand_id' => 4,
                'images' => ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400',
                'categories' => ['diver', 'men', 'sports', 'automatic'],
            ],
            [
                'name' => 'Himalayan Horology Everest Edition',
                'slug' => 'himlayan-horology-everest-edition',
                'description' => 'Limited edition timepiece inspired by the world\'s highest peak.',
                'short_description' => 'Luxury watch with mountain-inspired design and Swiss movement.',
                'sku' => 'HH-EV-001',
                'price' => 85000,
                'compare_price' => 100000,
                'final_price' => 85000,
                'discount_percentage' => 15,
                'stock_quantity' => 5,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_best_seller' => false,
                'is_limited_edition' => true,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Titanium',
                'case_diameter' => '42mm',
                'case_thickness' => '11mm',
                'water_resistance' => '100m',
                'dial_color' => 'Silver',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '5 years',
                'average_rating' => 4.9,
                'reviews_count' => 8,
                'brand_id' => 8,
                'images' => ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400',
                'categories' => ['nepali-heritage', 'unisex', 'limited-edition', 'luxury'],
            ],
            [
                'name' => 'Citizen Eco-Drive',
                'slug' => 'citizen-eco-drive',
                'description' => 'Solar-powered watch that never needs a battery replacement.',
                'short_description' => 'Eco-Drive technology with perpetual calendar.',
                'sku' => 'CTZ-ED-001',
                'price' => 28000,
                'compare_price' => 32000,
                'final_price' => 28000,
                'discount_percentage' => 13,
                'stock_quantity' => 30,
                'in_stock' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Solar',
                'strap' => 'Stainless Steel',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '40mm',
                'case_thickness' => '9mm',
                'water_resistance' => '100m',
                'dial_color' => 'Blue',
                'glass_type' => 'Mineral Crystal',
                'warranty_period' => '5 years',
                'average_rating' => 4.3,
                'reviews_count' => 92,
                'brand_id' => 5,
                'images' => ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400',
                'categories' => ['unisex', 'quartz'],
            ],
            [
                'name' => 'Rolex Daytona',
                'slug' => 'rolex-daytona',
                'description' => 'The ultimate chronograph watch with tachymeter bezel.',
                'short_description' => 'Iconic racing chronograph with Oystersteel construction.',
                'sku' => 'RLX-116500LN',
                'price' => 680000,
                'compare_price' => 720000,
                'final_price' => 680000,
                'discount_percentage' => 6,
                'stock_quantity' => 3,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Automatic',
                'strap' => 'Oystersteel',
                'case_material' => 'Oystersteel',
                'case_diameter' => '40mm',
                'case_thickness' => '12.5mm',
                'water_resistance' => '100m',
                'dial_color' => 'White',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '5 years',
                'average_rating' => 4.9,
                'reviews_count' => 78,
                'brand_id' => 1,
                'images' => ['https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=400',
                'categories' => ['luxury', 'chronograph', 'men', 'sports'],
            ],
            [
                'name' => 'Omega Seamaster Diver 300M',
                'slug' => 'omega-seamaster-diver-300m',
                'description' => 'Professional diving watch with wave-pattern dial.',
                'short_description' => '300m water resistance with helium escape valve.',
                'sku' => 'OMG-21030422001001',
                'price' => 320000,
                'compare_price' => null,
                'final_price' => 320000,
                'discount_percentage' => 0,
                'stock_quantity' => 6,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_best_seller' => false,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Automatic',
                'strap' => 'Stainless Steel',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '42mm',
                'case_thickness' => '13.5mm',
                'water_resistance' => '300m',
                'dial_color' => 'Blue',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '5 years',
                'average_rating' => 4.7,
                'reviews_count' => 56,
                'brand_id' => 2,
                'images' => ['https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=400',
                'categories' => ['luxury', 'diver', 'men', 'automatic'],
            ],
            [
                'name' => 'Seiko Presage Cocktail Time',
                'slug' => 'seiko-presage-cocktail-time',
                'description' => 'Elegant dress watch with a stunning sunburst dial.',
                'short_description' => 'Japanese craftsmanship meets classic design.',
                'sku' => 'SKX-SRP843',
                'price' => 35000,
                'compare_price' => null,
                'final_price' => 35000,
                'discount_percentage' => 0,
                'stock_quantity' => 15,
                'in_stock' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_best_seller' => false,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '38mm',
                'case_thickness' => '11mm',
                'water_resistance' => '50m',
                'dial_color' => 'Blue',
                'glass_type' => 'Hardlex Crystal',
                'warranty_period' => '2 years',
                'average_rating' => 4.5,
                'reviews_count' => 42,
                'brand_id' => 4,
                'images' => ['https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=400',
                'categories' => ['dress', 'unisex', 'automatic'],
            ],
            [
                'name' => 'Tag Heuer Aquaracer',
                'slug' => 'tag-heuer-aquaracer',
                'description' => 'Professional diving watch with robust design.',
                'short_description' => '300m diver with automatic movement and ceramic bezel.',
                'sku' => 'TH-AQR-001',
                'price' => 165000,
                'compare_price' => 180000,
                'final_price' => 165000,
                'discount_percentage' => 8,
                'stock_quantity' => 9,
                'in_stock' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Automatic',
                'strap' => 'Stainless Steel',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '43mm',
                'case_thickness' => '12mm',
                'water_resistance' => '300m',
                'dial_color' => 'Blue',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '2 years',
                'average_rating' => 4.5,
                'reviews_count' => 48,
                'brand_id' => 3,
                'images' => ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
                'categories' => ['diver', 'men', 'sports', 'automatic'],
            ],
            [
                'name' => 'Citizen Eco-Drive Promaster',
                'slug' => 'citizen-eco-drive-promaster',
                'description' => 'Tough solar-powered diver with ISO certification.',
                'short_description' => '200m diver with Eco-Drive technology.',
                'sku' => 'CTZ-PM-001',
                'price' => 32000,
                'compare_price' => 38000,
                'final_price' => 32000,
                'discount_percentage' => 16,
                'stock_quantity' => 22,
                'in_stock' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_best_seller' => true,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'men',
                'movement' => 'Solar',
                'strap' => 'Rubber',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '44mm',
                'case_thickness' => '12mm',
                'water_resistance' => '200m',
                'dial_color' => 'Black',
                'glass_type' => 'Mineral Crystal',
                'warranty_period' => '5 years',
                'average_rating' => 4.4,
                'reviews_count' => 112,
                'brand_id' => 5,
                'images' => ['https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400',
                'categories' => ['diver', 'men', 'sports'],
            ],
            [
                'name' => 'Nepal Time Annapurna Edition',
                'slug' => 'nepal-time-annapurna-edition',
                'description' => 'Inspired by the majestic Annapurna mountain range.',
                'short_description' => 'Elegant automatic watch with mountain peak motif.',
                'sku' => 'NT-AE-003',
                'price' => 28000,
                'compare_price' => 32000,
                'final_price' => 28000,
                'discount_percentage' => 13,
                'stock_quantity' => 18,
                'in_stock' => true,
                'is_featured' => false,
                'is_new' => true,
                'is_best_seller' => false,
                'is_limited_edition' => false,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '39mm',
                'case_thickness' => '10mm',
                'water_resistance' => '50m',
                'dial_color' => 'Green',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '2 years',
                'average_rating' => 4.6,
                'reviews_count' => 19,
                'brand_id' => 6,
                'images' => ['https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=400',
                'categories' => ['nepali-heritage', 'unisex', 'automatic', 'dress'],
            ],
            [
                'name' => 'Kathmandu Watches Durbar Square',
                'slug' => 'kathmandu-watches-durbar-square',
                'description' => 'Inspired by the historic Durbar Square architecture.',
                'short_description' => 'Classic dress watch with intricate dial detailing.',
                'sku' => 'KW-DS-003',
                'price' => 42000,
                'compare_price' => 48000,
                'final_price' => 42000,
                'discount_percentage' => 13,
                'stock_quantity' => 7,
                'in_stock' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_best_seller' => false,
                'is_limited_edition' => true,
                'status' => 'active',
                'gender' => 'unisex',
                'movement' => 'Automatic',
                'strap' => 'Leather',
                'case_material' => 'Stainless Steel',
                'case_diameter' => '40mm',
                'case_thickness' => '10mm',
                'water_resistance' => '30m',
                'dial_color' => 'White',
                'glass_type' => 'Sapphire Crystal',
                'warranty_period' => '3 years',
                'average_rating' => 4.8,
                'reviews_count' => 11,
                'brand_id' => 7,
                'images' => ['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=800'],
                'thumbnail' => 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400',
                'categories' => ['nepali-heritage', 'unisex', 'limited-edition', 'dress'],
            ],
        ];

        $categoryMap = [];
        foreach (Category::all() as $cat) {
            $categoryMap[$cat->slug] = $cat->id;
        }

        foreach ($products as $data) {
            $categorySlugs = $data['categories'];
            unset($data['categories']);

            $product = Product::create($data);

            // Attach categories
            $catIds = [];
            foreach ($categorySlugs as $slug) {
                if (isset($categoryMap[$slug])) {
                    $catIds[] = $categoryMap[$slug];
                }
            }
            if (!empty($catIds)) {
                $product->categories()->attach($catIds);
            }
        }

        // ============================================================
        // BLOGS (matching frontend sample data)
        // ============================================================
        $blogs = [
            [
                'title' => 'The Art of Watch Collecting: A Beginner\'s Guide',
                'slug' => 'the-art-of-watch-collecting',
                'content' => 'Watch collecting is a fascinating hobby that combines passion for craftsmanship, history, and design. Whether you are a seasoned collector or just starting out, understanding the fundamentals is key to building a meaningful collection. Start by researching different brands and movements, set a budget, and focus on quality over quantity.',
                'excerpt' => 'Discover the fundamentals of building a meaningful watch collection.',
                'featured_image' => 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
                'author' => 'Rajesh Sharma',
                'meta_title' => 'The Art of Watch Collecting',
                'meta_description' => 'A comprehensive guide for beginners.',
                'published_at' => now()->subDays(10),
                'status' => 'published',
            ],
            [
                'title' => 'Top 5 Luxury Watches for 2024',
                'slug' => 'top-5-luxury-watches-2024',
                'content' => 'This year brings exciting new releases from the world\'s top watchmakers. From the iconic Rolex Submariner to the innovative Omega Speedmaster, 2024 promises to be an exceptional year for luxury timepieces. Explore our curated selection of the most sought-after watches of the year.',
                'excerpt' => 'Explore the most sought-after luxury timepieces of 2024.',
                'featured_image' => 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800',
                'author' => 'Priya Thapa',
                'meta_title' => 'Top 5 Luxury Watches 2024',
                'meta_description' => 'Our picks for the best luxury watches.',
                'published_at' => now()->subDays(15),
                'status' => 'published',
            ],
            [
                'title' => 'Understanding Watch Movements',
                'slug' => 'understanding-watch-movements',
                'content' => 'The heart of any watch is its movement. From mechanical to quartz, each type offers unique benefits. Automatic movements harness kinetic energy, quartz offers precision, and manual movements connect you to horological tradition. Understanding these differences helps you choose the perfect timepiece.',
                'excerpt' => 'Learn about different types of watch movements.',
                'featured_image' => 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800',
                'author' => 'Bikash Gurung',
                'meta_title' => 'Watch Movements Explained',
                'meta_description' => 'A detailed comparison of movements.',
                'published_at' => now()->subDays(20),
                'status' => 'published',
            ],
        ];

        foreach ($blogs as $data) {
            Blog::create($data);
        }

        // ============================================================
        // HERO SLIDERS
        // ============================================================
        $heroSliders = [
            [
                'title' => 'Timeless Elegance',
                'subtitle' => 'Premium Collection 2024',
                'description' => 'Discover watches that define luxury',
                'button_text' => 'Shop Now',
                'button_url' => '/shop',
                'image' => 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=1920&h=1080&fit=crop',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'Luxury Redefined',
                'subtitle' => 'New Arrivals',
                'description' => 'Explore the latest timepieces',
                'button_text' => 'Explore',
                'button_url' => '/shop',
                'image' => 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=1920&h=1080&fit=crop',
                'is_active' => true,
                'sort_order' => 2,
            ],
        ];

        foreach ($heroSliders as $data) {
            HeroSlider::create($data);
        }

        // ============================================================
        // SHIPPING DISTRICTS (Nepal)
        // ============================================================
        $nepalDistricts = [
            ['name' => 'Kathmandu', 'cost' => 100, 'delivery_days' => '1-2 days'],
            ['name' => 'Lalitpur', 'cost' => 100, 'delivery_days' => '1-2 days'],
            ['name' => 'Bhaktapur', 'cost' => 100, 'delivery_days' => '1-2 days'],
            ['name' => 'Pokhara', 'cost' => 150, 'delivery_days' => '2-3 days'],
            ['name' => 'Chitwan', 'cost' => 150, 'delivery_days' => '2-3 days'],
            ['name' => 'Bharatpur', 'cost' => 150, 'delivery_days' => '2-3 days'],
            ['name' => 'Birgunj', 'cost' => 200, 'delivery_days' => '3-4 days'],
            ['name' => 'Biratanagar', 'cost' => 250, 'delivery_days' => '3-5 days'],
            ['name' => 'Butwal', 'cost' => 200, 'delivery_days' => '3-4 days'],
            ['name' => 'Dharan', 'cost' => 250, 'delivery_days' => '3-5 days'],
            ['name' => 'Janakpur', 'cost' => 200, 'delivery_days' => '3-4 days'],
            ['name' => 'Nepalgunj', 'cost' => 250, 'delivery_days' => '4-5 days'],
            ['name' => 'Hetauda', 'cost' => 150, 'delivery_days' => '2-3 days'],
            ['name' => 'Dhangadhi', 'cost' => 300, 'delivery_days' => '4-6 days'],
            ['name' => 'Birendranagar', 'cost' => 250, 'delivery_days' => '4-5 days'],
            ['name' => 'Tulsipur', 'cost' => 250, 'delivery_days' => '4-5 days'],
            ['name' => 'Ghorahi', 'cost' => 250, 'delivery_days' => '4-5 days'],
            ['name' => 'Itahari', 'cost' => 250, 'delivery_days' => '3-5 days'],
            ['name' => 'Bhairahawa', 'cost' => 200, 'delivery_days' => '3-4 days'],
            ['name' => 'Damak', 'cost' => 250, 'delivery_days' => '3-5 days'],
        ];

        foreach ($nepalDistricts as $data) {
            ShippingDistrict::create($data);
        }

        // ============================================================
        // FOOTER SETTINGS (Default footer configuration)
        // ============================================================
        FooterSetting::create([
            'brand_name' => 'WATCHSTORE',
            'brand_description' => 'Your premier destination for luxury watches in Nepal. Authentic timepieces from world-renowned brands.',
            'facebook_url' => 'https://facebook.com/watchstore',
            'instagram_url' => 'https://instagram.com/watchstore',
            'twitter_url' => 'https://twitter.com/watchstore',
            'quick_links' => [
                ['label' => 'Shop All', 'url' => '/shop'],
                ['label' => 'Brands', 'url' => '/brands'],
                ['label' => 'Blog', 'url' => '/blog'],
                ['label' => 'About Us', 'url' => '/about'],
                ['label' => 'Contact', 'url' => '/contact'],
            ],
            'customer_service_links' => [
                ['label' => 'Customer Service', 'url' => '/customer-service'],
                ['label' => 'Track Order', 'url' => '/track-order'],
                ['label' => 'FAQ', 'url' => '/faq'],
                ['label' => 'Shipping Info', 'url' => '/shipping'],
                ['label' => 'Returns & Exchanges', 'url' => '/returns'],
                ['label' => 'Privacy Policy', 'url' => '/privacy-policy'],
                ['label' => 'Terms & Conditions', 'url' => '/terms'],
            ],
            'phone' => '+977-1-4XXXXXX',
            'whatsapp_number' => '+977-9800000000',
            'email' => 'info@watchstore.com.np',
            'address' => 'Kathmandu, Nepal',
            'copyright_text' => 'WatchStore Nepal. All rights reserved.',
            'payment_methods' => [
                ['name' => 'eSewa'],
                ['name' => 'Khalti'],
                ['name' => 'COD'],
            ],
            'is_active' => true,
        ]);
    }
}
